openapi: 3.0.3
info:
  nom: STD23097 - TD1
  version: 1.0.0
server:
  URL: "https://localhost.STD23097.com"
path:
  /customers:
    get:
      response:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/customer"
  components:
    schema:
      customer:
        type: object
        properties:
          name:
            type: String
          age:
            type: Integer
